# Generated by Django 3.2.20 on 2023-09-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230913_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stadium',
            field=models.CharField(default='Unknown', max_length=150),
        ),
        migrations.AddField(
            model_name='post',
            name='team',
            field=models.CharField(default='Unknown', max_length=150),
        ),
    ]
